### ISSUE TITLE
Is This Broken On 29.4?

### ISSUE THREAD

**Issue by eeriemyxi** [wbolster/emacs-evil-colemak-basics#27]
Hi, this is my `init.el`:
```lisp
(add-to-list 'package-archives 
    '("MELPA" .
      "http://melpa.org/packages/"))
(package-initialize)

;; theme
(use-package gruvbox-theme :ensure t :config (load-theme 'gruvbox-dark-medium t))
;; font
(set-frame-font "JetBrainsMono Nerd Font Mono 13" nil t)

;; packages
(use-package evil :ensure t :config (evil-mode 1))
(use-package evil-colemak-basics
  :config
  (global-evil-colemak-basics-mode))
```
But when I start my Emacs it is not changing the keybinds as described in the README. _However_ if I execute `M-x global-evil-colemak-basics-mode` it starts working. I am not sure what's wrong with my config. Is this a bug or some misconfiguration on my behalf? Sorry if it's the latter but I am new to Emacs. How do I fix it?

**Comment by eeriemyxi** [comment]
If I open a new buffer it works which works fine for my purposes. However it doesn't work on the default startup buffer of Emacs. But I can work around that by simply disabling it entirely. Anyway if you wish to do something about it, you're free to re-open this issue. Thanks for your work!

**Comment by wbolster** [comment]
i don't see anything weird in your example. maybe try adding `:ensure t`?
